### PR TITLE
Gettin rid of static analysis warning

### PR DESCRIPTION
**Pull request by PatrickChrestin**
First of all, thank you very much for this amazing package. I am currently using it in a small project of mine and it works great!

When checking on pub.dev if there was a new version, I saw that the package only got 140/160 pub points.
The reason for this was a linter warning.
I opted for the proposed solution of the warning in a single line of code.

It is a small contribution to a great project.

Kind regards

### CODE REVIEW

**Comment by escamoteur** [comment]
thanks a lot!!

**Comment by escamoteur** [comment]
just pushed V1.6.1

**Comment by PatrickChrestin** [comment]
Wow that was fast! Nice to see that this repo is so actively managed 👍

**Comment by escamoteur** [comment]
I try my best and I'm really grateful for anyone helping.

**Pull request merged**
